repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: htmlhint
        name: htmlhint
        entry: htmlhint
        language: node
        additional_dependencies:
          - htmlhint@1.1.4
        files: \.html$

      - id: stylelint
        name: stylelint
        entry: stylelint
        language: node
        additional_dependencies:
          - stylelint@16.14.1
          - stylelint-config-standard@36.0.1
        files: \.css$

      - id: eslint
        name: eslint
        entry: eslint --max-warnings=0
        language: node
        additional_dependencies:
          - eslint@8.57.1
        files: \.js$
